# Generated by Django 5.0.6 on 2024-06-29 20:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('liked_by', models.CharField(default=None, max_length=500)),
                ('reference_type', models.CharField(default=None, max_length=256)),
                ('reference_id', models.UUIDField(default=None, null=True)),
            ],
        ),
    ]
