from enum import Enum

class ReferenceTypes(Enum):
    POST_REFERENCE_TYPE = 'POST'
    COMMENT_REFERENCE_TYPE = 'COMMENT'

class ErrorResponseStatus(Enum):
    INVALID_FIELD = 'INVALID_FIELD'
    DISCUSSION_NOT_FOUND = 'DISCUSSION_POST_NOT_FOUND'
    USER_NOT_FOUND = 'USER_NOT_FOUND'
    COMMENT_NOT_FOUND = 'COMMENT_NOT_FOUND'
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
    